In [1]:
#boosten

import pandas as pd
from sklearn.datasets import load_boston

In [7]:
boston_dataset=load_boston()

c:\users\deepak\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.
    :func:`~sklearn.datasets.fetch_california_housing`) and the Ames housing
    dataset. You can load the datasets as follows::

        from sklearn.datasets import fetch_california_housing
        housing = fetch_california_housing()

    for the California housing dataset and::

        from sklearn.datasets import fetch_openml
        housing = fetch_openml(name="house_prices", as_frame=True)

    for the Ames housing dataset.

  warnings.warn(msg, category=FutureWarning)

In [5]:
import numpy as np
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [9]:

from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()

In [10]:
df=pd.DataFrame(boston_dataset.data,columns=boston_dataset.feature_names)
df['MEDV']=boston_dataset.target

In [11]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,11.9

In [12]:
df.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [13]:
#train,test,split
from sklearn.model_selection import train_test_split
x=df.loc[:,df.columns!='MEDV']
y=df.loc[:,df.columns=='MEDV']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [14]:
#scale using minmaxscaler
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
x_train=mms.fit_transform(x_train)
x_test=mms.transform(x_test)

In [15]:
#define neural network
from keras.models import Sequential
from keras.layers import Dense

model=Sequential()
model.add(Dense(128,input_shape=(13,),activation='relu',name='dense_1'))
model.add(Dense(64,activation='relu',name='dense_2'))
model.add(Dense(1,activation='linear',name='dense_output'))

model.compile(optimizer='adam',loss='mse',metrics=['mae'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_1 (Dense)             (None, 128)               1792

 dense_2 (Dense)             (None, 64)                8256

 dense_output (Dense)        (None, 1)                 65

=================================================================
Total params: 10,113
Trainable params: 10,113
Non-trainable params: 0
_________________________________________________________________

In [16]:
#train model
history=model.fit(x_train,y_train,epochs=100,verbose=1)

Epoch 1/100
12/12 [==============================] - 2s 5ms/step - loss: 558.1313 - mae: 21.8572
Epoch 2/100
12/12 [==============================] - 0s 6ms/step - loss: 497.1106 - mae: 20.3718
Epoch 3/100
12/12 [==============================] - 0s 6ms/step - loss: 411.0838 - mae: 17.9942
Epoch 4/100
12/12 [==============================] - 0s 4ms/step - loss: 293.4848 - mae: 14.2410
Epoch 5/100
12/12 [==============================] - 0s 4ms/step - loss: 180.3926 - mae: 10.4422
Epoch 6/100
12/12 [==============================] - 0s 4ms/step - loss: 125.7087 - mae: 8.5638
Epoch 7/100
12/12 [==============================] - 0s 4ms/step - loss: 113.8730 - mae: 8.1583
Epoch 8/100
12/12 [==============================] - 0s 4ms/step - loss: 97.6968 - mae: 7.3953
Epoch 9/100
12/12 [==============================] - 0s 4ms/step - loss: 84.6172 - mae: 6.6675
Epoch 10/100
12/12 [==============================] - 0s 4ms/step - loss: 75.2943 - mae: 6.1532
Epoch 11/100
12/12 [==============================] - 0s 5ms/step - loss: 67.2850 - mae: 5.8298
Epoch 12/100
12/12 [==============================] - 0s 4ms/step - loss: 60.9855 - mae: 5.6043
Epoch 13/100
12/12 [==============================] - 0s 4ms/step - loss: 57.8347 - mae: 5.6387
Epoch 14/100
12/12 [==============================] - 0s 4ms/step - loss: 52.9276 - mae: 5.3022
Epoch 15/100
12/12 [==============================] - 0s 4ms/step - loss: 50.2894 - mae: 4.9015
Epoch 16/100
12/12 [==============================] - 0s 4ms/step - loss: 48.4785 - mae: 4.7892
Epoch 17/100
12/12 [==============================] - 0s 4ms/step - loss: 46.8691 - mae: 4.7631
Epoch 18/100
12/12 [==============================] - 0s 4ms/step - loss: 45.6992 - mae: 4.6212
Epoch 19/100
12/12 [==============================] - 0s 4ms/step - loss: 44.1998 - mae: 4.5921
Epoch 20/100
12/12 [==============================] - 0s 4ms/step - loss: 42.4726 - mae: 4.6066
Epoch 21/100
12/12 [==============================] - 0s 5ms/step - loss: 41.3001 - mae: 4.5357
Epoch 22/100
12/12 [==============================] - 0s 4ms/step - loss: 39.5631 - mae: 4.4225
Epoch 23/100
12/12 [==============================] - 0s 4ms/step - loss: 38.2452 - mae: 4.3037
Epoch 24/100
12/12 [==============================] - 0s 5ms/step - loss: 36.9771 - mae: 4.2955
Epoch 25/100
12/12 [==============================] - 0s 5ms/step - loss: 35.5020 - mae: 4.1638
Epoch 26/100
12/12 [==============================] - 0s 4ms/step - loss: 34.2970 - mae: 4.2258
Epoch 27/100
12/12 [==============================] - 0s 4ms/step - loss: 33.6652 - mae: 4.2791
Epoch 28/100
12/12 [==============================] - 0s 4ms/step - loss: 31.9535 - mae: 3.8636
Epoch 29/100
12/12 [==============================] - 0s 4ms/step - loss: 30.7839 - mae: 3.7596
Epoch 30/100
12/12 [==============================] - 0s 4ms/step - loss: 29.4774 - mae: 3.7079
Epoch 31/100
12/12 [==============================] - 0s 4ms/step - loss: 28.1973 - mae: 3.7043
Epoch 32/100
12/12 [==============================] - 0s 5ms/step - loss: 27.1745 - mae: 3.6153
Epoch 33/100
12/12 [==============================] - 0s 4ms/step - loss: 26.2839 - mae: 3.5841
Epoch 34/100
12/12 [==============================] - 0s 4ms/step - loss: 25.5341 - mae: 3.4288
Epoch 35/100
12/12 [==============================] - 0s 4ms/step - loss: 24.5496 - mae: 3.5430
Epoch 36/100
12/12 [==============================] - 0s 4ms/step - loss: 23.3629 - mae: 3.3890
Epoch 37/100
12/12 [==============================] - 0s 4ms/step - loss: 22.7578 - mae: 3.4037
Epoch 38/100
12/12 [==============================] - 0s 4ms/step - loss: 21.8612 - mae: 3.2499
Epoch 39/100
12/12 [==============================] - 0s 4ms/step - loss: 21.1004 - mae: 3.1958
Epoch 40/100
12/12 [==============================] - 0s 4ms/step - loss: 20.6114 - mae: 3.1292
Epoch 41/100
12/12 [==============================] - 0s 5ms/step - loss: 20.1573 - mae: 3.1390
Epoch 42/100
12/12 [==============================] - 0s 4ms/step - loss: 19.5961 - mae: 3.0604
Epoch 43/100
12/12 [==============================] - 0s 5ms/step - loss: 19.5516 - mae: 3.1597
Epoch 44/100
12/12 [==============================] - 0s 4ms/step - loss: 19.7331 - mae: 3.0358
Epoch 45/100
12/12 [==============================] - 0s 4ms/step - loss: 18.8927 - mae: 3.1130
Epoch 46/100
12/12 [==============================] - 0s 4ms/step - loss: 18.4911 - mae: 2.9912
Epoch 47/100
12/12 [==============================] - 0s 4ms/step - loss: 18.3553 - mae: 3.0294
Epoch 48/100
12/12 [==============================] - 0s 3ms/step - loss: 18.0916 - mae: 2.9074
Epoch 49/100
12/12 [==============================] - 0s 4ms/step - loss: 17.8943 - mae: 2.9999
Epoch 50/100
12/12 [==============================] - 0s 5ms/step - loss: 17.5811 - mae: 2.8883
Epoch 51/100
12/12 [==============================] - 0s 4ms/step - loss: 17.5539 - mae: 2.8573
Epoch 52/100
12/12 [==============================] - 0s 4ms/step - loss: 17.2686 - mae: 2.8578
Epoch 53/100
12/12 [==============================] - 0s 4ms/step - loss: 17.2509 - mae: 2.8400
Epoch 54/100
12/12 [==============================] - 0s 4ms/step - loss: 16.9342 - mae: 2.8645
Epoch 55/100
12/12 [==============================] - 0s 4ms/step - loss: 17.0184 - mae: 2.7939
Epoch 56/100
12/12 [==============================] - 0s 3ms/step - loss: 16.7310 - mae: 2.8667
Epoch 57/100
12/12 [==============================] - 0s 5ms/step - loss: 16.5631 - mae: 2.8303
Epoch 58/100
12/12 [==============================] - 0s 4ms/step - loss: 16.6293 - mae: 2.8650
Epoch 59/100
12/12 [==============================] - 0s 4ms/step - loss: 16.2955 - mae: 2.7819
Epoch 60/100
12/12 [==============================] - 0s 4ms/step - loss: 16.2801 - mae: 2.8150
Epoch 61/100
12/12 [==============================] - 0s 4ms/step - loss: 16.2029 - mae: 2.7444
Epoch 62/100
12/12 [==============================] - 0s 4ms/step - loss: 16.2189 - mae: 2.7446
Epoch 63/100
12/12 [==============================] - 0s 4ms/step - loss: 15.8350 - mae: 2.7329
Epoch 64/100
12/12 [==============================] - 0s 4ms/step - loss: 15.6498 - mae: 2.7202
Epoch 65/100
12/12 [==============================] - 0s 4ms/step - loss: 15.7651 - mae: 2.6734
Epoch 66/100
12/12 [==============================] - 0s 4ms/step - loss: 15.6025 - mae: 2.7269
Epoch 67/100
12/12 [==============================] - 0s 4ms/step - loss: 15.5477 - mae: 2.6661
Epoch 68/100
12/12 [==============================] - 0s 4ms/step - loss: 15.3874 - mae: 2.7377
Epoch 69/100
12/12 [==============================] - 0s 5ms/step - loss: 15.1276 - mae: 2.6409
Epoch 70/100
12/12 [==============================] - 0s 4ms/step - loss: 15.7932 - mae: 2.8603
Epoch 71/100
12/12 [==============================] - 0s 4ms/step - loss: 15.2271 - mae: 2.6313
Epoch 72/100
12/12 [==============================] - 0s 4ms/step - loss: 14.7609 - mae: 2.6264
Epoch 73/100
12/12 [==============================] - 0s 4ms/step - loss: 14.7398 - mae: 2.6323
Epoch 74/100
12/12 [==============================] - 0s 5ms/step - loss: 14.5201 - mae: 2.6241
Epoch 75/100
12/12 [==============================] - 0s 4ms/step - loss: 14.5996 - mae: 2.6198
Epoch 76/100
12/12 [==============================] - 0s 4ms/step - loss: 16.2405 - mae: 2.9363
Epoch 77/100
12/12 [==============================] - 0s 4ms/step - loss: 14.8800 - mae: 2.6167
Epoch 78/100
12/12 [==============================] - 0s 4ms/step - loss: 14.4983 - mae: 2.6442
Epoch 79/100
12/12 [==============================] - 0s 4ms/step - loss: 15.1665 - mae: 2.6117
Epoch 80/100
12/12 [==============================] - 0s 4ms/step - loss: 14.1657 - mae: 2.6204
Epoch 81/100
12/12 [==============================] - 0s 3ms/step - loss: 14.1121 - mae: 2.5627
Epoch 82/100
12/12 [==============================] - 0s 5ms/step - loss: 13.9603 - mae: 2.5619
Epoch 83/100
12/12 [==============================] - 0s 4ms/step - loss: 13.9838 - mae: 2.5424
Epoch 84/100
12/12 [==============================] - 0s 4ms/step - loss: 14.2061 - mae: 2.6442
Epoch 85/100
12/12 [==============================] - 0s 4ms/step - loss: 16.1599 - mae: 3.0034
Epoch 86/100

12/12 [==============================] - 0s 4ms/step - loss: 14.5662 - mae: 2.6433
Epoch 87/100
12/12 [==============================] - 0s 4ms/step - loss: 14.1448 - mae: 2.7008
Epoch 88/100
12/12 [==============================] - 0s 4ms/step - loss: 13.8258 - mae: 2.5105
Epoch 89/100
12/12 [==============================] - 0s 4ms/step - loss: 15.3205 - mae: 2.8922
Epoch 90/100
12/12 [==============================] - 0s 5ms/step - loss: 13.9620 - mae: 2.5616
Epoch 91/100
12/12 [==============================] - 0s 4ms/step - loss: 13.3090 - mae: 2.5558
Epoch 92/100
12/12 [==============================] - 0s 5ms/step - loss: 13.1093 - mae: 2.5034
Epoch 93/100
12/12 [==============================] - 0s 6ms/step - loss: 13.1011 - mae: 2.4849
Epoch 94/100
12/12 [==============================] - 0s 4ms/step - loss: 13.1698 - mae: 2.5592
Epoch 95/100
12/12 [==============================] - 0s 4ms/step - loss: 13.2079 - mae: 2.4404
Epoch 96/100
12/12 [==============================] - 0s 3ms/step - loss: 13.2834 - mae: 2.6088
Epoch 97/100
12/12 [==============================] - 0s 4ms/step - loss: 13.1619 - mae: 2.4462
Epoch 98/100
12/12 [==============================] - 0s 3ms/step - loss: 12.7900 - mae: 2.4873
Epoch 99/100
12/12 [==============================] - 0s 4ms/step - loss: 12.8144 - mae: 2.5225
Epoch 100/100
12/12 [==============================] - 0s 3ms/step - loss: 13.3673 - mae: 2.6447

In [17]:
#evaluate
mse,mae=model.evaluate(x_test,y_test)

print('MSE : ',mse)
print('MAE : ',mae)

5/5 [==============================] - 0s 4ms/step - loss: 24.0601 - mae: 3.0752
MSE :  24.06011962890625
MAE :  3.075228452682495

In [18]:
y_test

     MEDV
167  23.8
188  29.8
377  13.3
120  22.0
42   25.3
..    ...
345  17.5
211  19.3
293  23.9
47   16.6
252  29.6

[152 rows x 1 columns]

In [19]:
y1=model.predict(x_test[:])

5/5 [==============================] - 0s 5ms/step

In [20]:
ps=[]
for i in y1:
    ps.append(list(i)[0])

In [21]:
d=pd.DataFrame({'Actual':y_test['MEDV'],'Predicted':ps})
d

     Actual  Predicted
167    23.8  17.970346
188    29.8  31.205374
377    13.3  17.811895
120    22.0  19.544249
42     25.3  25.166050
..      ...        ...
345    17.5  18.416037
211    19.3  14.618115
293    23.9  24.297258
47     16.6  17.444345
252    29.6  28.533134

[152 rows x 2 columns]